### PR TITLE
isolated build of decoderbufs

### PR DESCRIPTION
**Pull request by nightlyone**
by using Docker
so the plugin is put in the correct destionation directory and can be
extracted or used from there.

build: 
```shell
docker build -t decoderbufs:latest -f Dockerfile.build .
```
run:
```shell
docker volume create pgdata
docker run -it --rm -v pgdata:/var/lib/postgresql/data decoderbufs:latest
```

### CODE REVIEW

**Comment by nightlyone** [comment]
Note: I still don't know how to put config files there, so it's work in progress.

**Comment by nightlyone** [comment]
Postgresql configs are now provided.

**Comment by nightlyone** [comment]
@krzychk FYI

**Comment by danchel** [comment]
looks good for me

**Pull request merged**
